[package]
name = "dbug"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.2", features = ["derive"] }
indicatif = "0.17.2"
probe-rs = "0.13.0"
comfy-table = "6.1.4"
packed_struct = "0.10.1"
jep106 = "0.2.8"
svd-parser = "0.14.1"
